"""Sourceless launcher. Generated by scripts/obfuscate_project.py."""
from __future__ import annotations
import importlib.util
import pathlib
import sys

REQUIRED = (3, 10)


def _run_pyc() -> None:
    if sys.implementation.name != "cpython" or sys.version_info[:2] != REQUIRED:
        raise SystemExit(
            "This release was built for CPython "
            f"{REQUIRED[0]}.{REQUIRED[1]}.x, current is {sys.version.split()[0]}."
        )
    pyc = pathlib.Path(__file__).with_suffix(".pyc")
    spec = importlib.util.spec_from_file_location("__main__", pyc)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load {pyc}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["__main__"] = module
    spec.loader.exec_module(module)


if __name__ == "__main__":
    _run_pyc()
